### ISSUE TITLE
Doesn't work with Esphome 2021.8.0

### ISSUE THREAD

**Issue by torrottum** [torrottum/ikea-ansluta-esphome#23]
```
src/esphome/components/ikea_ansluta/light/light.cpp: In member function 'virtual esphome::light::LightTraits esphome::ikea_ansluta::Light::get_traits()':
src/esphome/components/ikea_ansluta/light/light.cpp:28:10: error: 'class esphome::light::LightTraits' has no member named 'set_supports_brightness'
   traits.set_supports_brightness(true);
          ^
*** [/data/kitchen_counter/.pioenvs/kitchen_counter/src/esphome/components/ikea_ansluta/light/light.cpp.o] Error 1
```
Need to change to the new color modes.
In both v1 and v2
